name: CI
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      CODEBOOK_PATH: data/codebooks/icd10cm_codes_enriched_sample.csv

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install -U pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt || true

      - name: Lint
        run: |
          ruff check .
          ruff format --check .

      - name: Verify ICD-10 codebook
        run: |
          python - <<'PY'
          import os, pathlib, pandas as pd
          p = pathlib.Path(os.environ["CODEBOOK_PATH"])
          print("Using:", p, "exists:", p.exists())
          df = pd.read_csv(p)
          required = {"code","short_title","long_title"}
          missing = required - set(df.columns)
          if missing:
              raise SystemExit(f"Missing columns: {missing}")
          print("CSV rows:", len(df))
          PY

      - name: Run tests
        env:
          PYTHONPATH: ${{ github.workspace }}
        run: pytest -q
