name: CI
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PYTHONPATH: ${{ github.workspace }} # ensure 'services' package resolves
      CODEBOOK_PATH: data/codebooks/icd10cm_codes_enriched_sample.csv

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Upgrade build tooling
        run: python -m pip install --upgrade pip setuptools wheel

      - name: Install deps
        run: |
          python -m pip install -r requirements.txt
          if [ -f requirements-dev.txt ]; then python -m pip install -r requirements-dev.txt; fi
          python -m pip install ruff

      - name: Lint
        run: |
          python -m ruff --version
          python -m ruff check .
          python -m ruff format --check .

      - name: Show versions
        run: |
          python - <<'PY'
          import sys, platform, pandas, numpy, sklearn, fastapi, pytest
          print("python:", sys.version)
          print("platform:", platform.platform())
          print("pandas:", pandas.__version__)
          print("numpy:", numpy.__version__)
          print("sklearn:", sklearn.__version__)
          print("fastapi:", fastapi.__version__)
          print("pytest:", pytest.__version__)
          PY

      - name: Show workspace tree (debug)
        run: |
          echo "PWD: $(pwd)"
          ls -la
          echo "---- data/codebooks ----"
          ls -la data || true
          ls -la data/codebooks || true
          echo "CODEBOOK_PATH=${CODEBOOK_PATH}"

      - name: Validate codebook CSV
        run: |
          python - <<'PY'
          import os, pandas as pd, pathlib
          p = pathlib.Path(os.environ["CODEBOOK_PATH"])
          print("CSV exists:", p.exists(), "->", p)
          df = pd.read_csv(p)
          required = {"code","short_title","long_title"}
          missing = required - set(df.columns)
          if missing:
              raise SystemExit(f"Missing columns: {missing} (have {list(df.columns)})")
          print("CSV rows:", len(df))
          PY

      - name: Import app & show codebook used
        run: |
          python - <<'PY'
          from pathlib import Path
          import services.coder_api.app as app
          print("APP_VERSION:", getattr(app, "APP_VERSION", "?"))
          app_path = getattr(app, "CODEBOOK_PATH", None)
          if app_path is not None:
              try:
                  p = Path(app_path)
              except TypeError:
                  p = Path(str(app_path))
              print("App CODEBOOK_PATH:", p, "exists:", p.exists())
          else:
              print("App CODEBOOK_PATH not exposed on module.")
          PY

      - name: Test discovery
        run: pytest -q --collect-only

      - name: Run tests
        run: pytest -q -vv
